### PR TITLE
add postgres

### PR DESCRIPTION
**Pull request by k--kato**
- [x] add PostgreSQL

vscode_database_postgres

### CODE REVIEW

**Comment by Bajdzis** [comment]
Good job! I started merge you changes! :D

**Comment by k--kato** [comment]
Thanks and thank you that extension is awesome! :)

**Comment by Bajdzis** [comment]
I done. Please download my change from branch 
https://github.com/Bajdzis/vscode-database/tree/dev-postgres and testing postgres server.

**Comment by k--kato** [comment]
@Bajdzis LGTM! I found some issues and fixed (PR #6.)

**Comment by k--kato** [comment]
@Bajdzis Postgres server test, all green.

**Pull request merged**
